name: Continuous-Integration

on:
  push:
    branches:
      - main

jobs:
  lint_and_test:
    name: Linting, Testing, and Django Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Linting with PyLint
        run: pylint ./User

      - name: Start Django server
        run: |
          python manage.py migrate
          python manage.py runserver &
          sleep 10

      - name: Run tests with pytest
        run: pytest
